"""Initial migration with User and ContentKeys tables

Revision ID: 8ed863efdbdb
Revises: 
Create Date: 2025-09-20 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ed863efdbdb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - MANUALLY CORRECTED ###
    
    # First, create the 'user' table
    op.create_table('user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(length=80), nullable=False),
        sa.Column('password_hash', sa.String(length=200), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('username')
    )

    # Second, create the 'content_keys' table, including the foreign key from the start
    op.create_table('content_keys',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('key_name', sa.String(length=100), nullable=False),
        sa.Column('display_name', sa.String(length=200), nullable=False),
        sa.Column('original_filename', sa.String(length=200), nullable=False),
        sa.Column('secure_filename', sa.String(length=200), nullable=False),
        sa.Column('file_size', sa.Integer(), nullable=False),
        sa.Column('password_hash', sa.String(length=200), nullable=True),
        sa.Column('expires_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        # Define the foreign key relationship here
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_content_keys_user_id'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('key_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - MANUALLY CORRECTED ###
    op.drop_table('content_keys')
    op.drop_table('user')
    # ### end Alembic commands ###